In [ ]:
import tensorflow_datasets as tfds

# Load iris dataset
iris = tfds.load('iris', as_supervised=True)

# Take one example
for features, label in iris['train'].take(1):
    print(type(features))  # <class 'tensorflow.python.framework.ops.EagerTensor'>
    print(features)
    print(type(label))     # <class 'tensorflow.python.framework.ops.EagerTensor'>
    print(label)

/Users/dinaeshs/Desktop/30_Day_of_AI/30dayai/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Dl Completed...: 0 url [00:00, ? url/s]
Dl Completed...: 100%|██████████| 1/1 [00:19<00:00, 19.81s/ url]

Extraction completed...: 100%|██████████| 4/4 [00:19<00:00,  4.95s/ file]
Dl Size...: 0 MiB [00:19, ? MiB/s]
Dl Completed...: 100%|██████████| 1/1 [00:19<00:00, 19.81s/ url]
                                                                

Dataset iris downloaded and prepared to /Users/dinaeshs/tensorflow_datasets/iris/2.1.0. Subsequent calls will reuse this data.
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor([5.1 3.4 1.5 0.2], shape=(4,), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(0, shape=(), dtype=int64)


2025-08-15 19:37:39.530400: I tensorflow/core/kernels/data/tf_record_dataset_op.cc:396] The default buffer size is 262144, which is overridden by the user specified `buffer_size` of 8388608
2025-08-15 19:37:39.531753: W tensorflow/core/kernels/data/cache_dataset_ops.cc:917] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
2025-08-15 19:37:39.532756: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [3]:
print(type(iris))

<class 'dict'>


In [1]:
import tensorflow as tf
from tensorflow.keras import layers, models


: 

Importing TensorFlow and its Keras submodules.

layers → lets you create neural network layers like Dense.

models → allows building models, like Sequential or Model.

In [5]:
model = models.Sequential([
    layers.Dense(8, activation='relu', input_shape=(4,)),  # input has 4 features
    layers.Dense(3, activation='softmax')                  # output 3 classes (for Iris)
])


/Users/dinaeshs/Desktop/30_Day_of_AI/30dayai/lib/python3.13/site-packages/keras/src/layers/core/dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Sequential → builds a model as a stack of layers in order.

First layer: Dense(8, activation='relu', input_shape=(4,))

Dense(8) → fully connected layer with 8 neurons.

activation='relu' → applies the ReLU activation to introduce non-linearity.

input_shape=(4,) → expects input vectors of size 4 (Iris dataset has 4 features).

Second layer: Dense(3, activation='softmax')

Dense(3) → output layer with 3 neurons (for 3 Iris classes).

activation='softmax' → converts outputs into probabilities that sum to 1.

In [6]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


optimizer='adam' → chooses the Adam optimizer, which adjusts weights to minimize loss.

loss='sparse_categorical_crossentropy' → suitable for multi-class classification when labels are integers (0,1,2).

metrics=['accuracy'] → track accuracy during training.

In [7]:
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 67 (268.00 B)

 Trainable params: 67 (268.00 B)

 Non-trainable params: 0 (0.00 B)

Your model is a Sequential model, meaning layers are stacked one after another.

Columns:

Layer (type) → the name of the layer and its type (Dense).

Output Shape → shape of the output tensor from that layer.

Param # → number of trainable parameters (weights + biases) in that layer.

first layer --

dense → first dense (fully connected) layer.

(None, 8) → output shape: 8 neurons; None is the batch size, which can vary.

Param # = 40 → calculated as:

Params=(input features×neurons)+biases= (4×8)+8=32+8=40


second layer :

dense_1 → output layer with 3 neurons (for 3 classes).

(None, 3) → 3 outputs per input sample.

Param # = 27 → calculated as:

Params=(inputs from previous layer×neurons)+biases=(8×3)+3=24+3=27

In [8]:
import numpy as np

# Example input: first 5 samples from Iris
X_new = np.array([[5.1, 3.5, 1.4, 0.2],
                  [6.2, 3.4, 5.4, 2.3],
                  [5.9, 3.0, 5.1, 1.8]])

# Get model predictions (probabilities)
pred_probs = model.predict(X_new)
print(pred_probs)

# Get predicted class labels
pred_classes = np.argmax(pred_probs, axis=1)
print(pred_classes)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
[[3.8690129e-01 2.3966043e-03 6.1070210e-01]
 [1.8467812e-01 1.4609456e-05 8.1530720e-01]
 [2.0749594e-01 3.7318845e-05 7.9246676e-01]]
[2 2 2]
